### PR TITLE
Test Cases for WebSocket

### LINKED ISSUE #222: Need Test Cases for WebSocket
We need to add test cases for WebSocket. Until now there is only one test case to test handshake.
We need to add test cases to check
- Text Message
- Binary Message
- Pong Message (Control Messages)
- New Connection (Status message for On Open)
- Close connection (Status message for On Close)

### PR DESCRIPTION
**Pull request by irunika**
resolves #222

### CODE REVIEW

**Comment by Kishanthan** [comment]
This should be merged for 4.3.0 release

**Review by Kishanthan — CHANGES_REQUESTED** [review]
This should be merged for 4.3.0 release

**Comment by Kishanthan** [comment]
Can you send this PR to transport-stabilize branch?

**Comment by irunika** [comment]
Closing this since PR is sent to transport-stabilize branch.

**Pull request closed without merging**
